services:
  chatbot:
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/
    image: errajibadr/chatbot_mvp:latest
    restart: no  # Add this line to ensure the container is not restarted after it stops


